apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.NameSpace }}
  name: {{ .Values.appName }}-service
  labels:
    app: {{ .Values.appName }}-service
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appName }}
