# Default values for pipeline-mock-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

NameSpace: "pipline-mock"
appName: pipline-mock-app

replicaCount: 1

image:
  repository: erdock1/pipeline-mock-public
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: dev.0.0.0.1-dev

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  port: 80
  targetPort: 5000

